WIP: `.zarr` dataset
cwognum/graphium pull request #1
Opened 2023-06-20 21:03 UTC by cwognum

2023-06-20 22:59 UTC, DomInvivo requested changes
Cool changes, hope it makes a difference in performance

2023-06-20 22:59 UTC, DomInvivo commented on graphium/data/dataset.py
> +                    # TODO (cwognum): Instead try to pad the arrays to a max length
I don't think maximal length makes sense considering how variable molecular sizes can be

2023-06-20 22:59 UTC, DomInvivo commented on graphium/data/dataset.py
> +        # Prioritize loading from a pickle file if it exists
I would suggest simply killing pickle support, and have a single strategy for saving/loading

2023-06-20 22:59 UTC, DomInvivo commented on graphium/data/dataset.py
> +        data_dict = {}
Since you have `to_zarr`, can you also add `from_zarr`? And if we keep pickle support, have `to_pickle` and `from_pickle` as well.

2023-06-20 22:59 UTC, DomInvivo commented on graphium/data/dataset.py
> +        # This assumes the dtype and keys across the data are the same.
This assumption generally works, but fails in this case:

In a multitask setting, not all molecules have data on all tasks. You should look at `self.labelsizes.keys()` to know what are the tasks.

2023-06-21 16:54 UTC, hadim commented on graphium/data/dataset.py
> +        # This assumes the dtype and keys across the data are the same.
Maybe having a metadata dataframe at the root of the zarr would help for this:

- `/metadata`: various metadata about the dataset
- /data`:
    - `/data/data_point_1`
    - `/data/data_point_2`
    - etc

2023-06-21 16:56 UTC, hadim commented on graphium/data/dataset.py
> +        data_dict = {}
I agree we should rely on a single file format. For now, I would suggest keeping exploring until we find the correct Zarr structure that indeed brings a performance bump before refactoring the data module.

2023-06-22 16:03 UTC, closed without merging